import { DefaultColor } from '../Core/Types';
import { DefaultTransform } from '../Transform/Transform.Types';
import type { JivStyle } from './Jiv.Types';

export const DefaultJivStyle: JivStyle = {
  Material: 'None',
  BorderRadius: [0, 0, 0, 0],
  CornerShape: ['Round', 'Round', 'Round', 'Round'],
  Smoothness: 0.6,
  Overflow: 'Visible',
  Background: DefaultColor,
  BlendMode: 'Normal',
  Frost: 0,
  BackdropFrostBlur: 0,
  Thickness: 0,
  Fillet: 0,
  Refraction: 0,
  BackdropBrightness: 1,
  BackdropSaturation: 1,
  BackdropContrast: 1,
  BezelWidth: 12,
  BezelScale: 0.35,
  LightAngle: -45,
  LightIntensity: 1,
  SpecularIntensity: 0,
  SpecularSharpness: 100,
  FresnelStrength: 0,
  ChromaticAberration: 0,
  EdgeLightTop: 0,
  EdgeLightBottom: 0,
  BorderVariance: 0,
  BorderAlphaVariance: 0,
  BorderFresnelBrightness: 0,
  InnerBlur: 0,
  Transform: { ...DefaultTransform },
  BorderColor: DefaultColor,
  BorderWidth: 0,
  BorderBlur: 0,
  BorderOffset: 0,
  ContainBorder: false,
  BorderBrightness: 1,
  BorderSaturation: 1,
  BorderContrast: 1,
  BorderFrostLodOffset: 0,
  ShadowColor: DefaultColor,
  ShadowBlur: 0,
  ShadowOffsetX: 0,
  ShadowOffsetY: 0,
  InnerShadow: false,
  Opacity: 1,
  Visible: true,
  Cursor: 'Default',
  Interactive: false,
  PointerEvents: 'Auto',
};
