/**
 * THE SS PILL ENDCAP, AS DATA THE PANEL SHADER READS FROM A UNIFORM.
 *
 * 33 (u, v) points along the upper-right quarter of Show Studio's pill endcap, in normalized
 * coordinates: u = horizontal distance from the flat zone's end / maxExtent (0..1), v = vertical
 * distance from the horizontal middle / halfY (0..1). Generated by tests/Pill.PolylineGen.test.ts;
 * do not hand-edit. 32 segments give sub-pixel accuracy on a 60-tall pill.
 *
 * WHY THIS IS A UNIFORM AND NOT A `const vec2[]` IN THE SHADER (2026-09-22). On Windows, ANGLE
 * translates a GLSL constant array into an HLSL `static` array -- not `static const` -- and FXC
 * then keeps it as an indexable temporary: it initializes all 66 floats on every invocation and
 * turns every lookup in the segment loop into an indexed scratch read. Measured with the SDK's
 * fxc.exe on ANGLE's own translation, that and the fixed 32-trip loop around it were the largest
 * single cost of compiling the panel shader; the pill appears three times in it (the shape, the
 * shadow and the clip stack). As a uniform the array lives in a constant buffer, and with the trip
 * count read from `u_PillSegments` the loop stays a loop. Cold, in real Chrome on D3D11: the glass
 * program 803 -> 649 ms, the seven panel variants together 1,313 -> 1,087 ms.
 *
 * The values are these same decimals, uploaded as float32, which is what the GLSL literals were
 * rounded to; the loop runs the same 32 iterations in the same order. The arithmetic is unchanged.
 */
export const SS_PILL_CURVE = new Float32Array([
  0.00000000, 1.00000000,
  0.04265581, 0.99999445,
  0.08531159, 0.99993035,
  0.12796709, 0.99969402,
  0.17062123, 0.99912542,
  0.21327087, 0.99802453,
  0.25590906, 0.99615489,
  0.29852244, 0.99324588,
  0.34108789, 0.98899457,
  0.38356831, 0.98306800,
  0.42590761, 0.97510672,
  0.46802503, 0.96473086,
  0.50980938, 0.95155004,
  0.55111404, 0.93517850,
  0.59175424, 0.91525605,
  0.63150841, 0.89147416,
  0.67012530, 0.86360450,
  0.70733754, 0.83152444,
  0.74288036, 0.79523315,
  0.77651200, 0.75485312,
  0.80803128, 0.71061553,
  0.83728806, 0.66283306,
  0.86418529, 0.61186710,
  0.88867327, 0.55809644,
  0.91073888, 0.50189257,
  0.93039268, 0.44360330,
  0.94765574, 0.38354448,
  0.96254728, 0.32199785,
  0.97507274, 0.25921346,
  0.98521039, 0.19541521,
  0.99289197, 0.13080918,
  0.99796172, 0.06559637,
  1.00000000, 0.00000000,
]);

/** Segments between the points: the pill SDF's loop bound, uploaded as `u_PillSegments`. */
export const SS_PILL_SEGMENTS = SS_PILL_CURVE.length / 2 - 1;
