import type { JivStyle } from './Jiv.Types';

export const DefaultJivStyle: JivStyle = {
  Material: 'None',
  // PointScale defaults to "1pt" — "inherit from parent's PointScale".
  // Root Jiv has no parent, so its `pt` refers to a hardcoded fallback (16)
  // inside the layout solver. Set PointScale to an absolute like "16" at
  // the root (or any subtree root) to rebase `pt` for that subtree.
  PointScale: '1pt',
  BorderRadius: '0',
  CornerShape: 'Round',
  BorderRadiusSmoothness: '0.3',
  Overflow: 'Visible',
  Background: 'rgba(0, 0, 0, 0)',
  BlendMode: 'Normal',
  Frost: '0',
  BackdropFrostBlur: '0',
  Thickness: '0',
  Fillet: '0',
  Refraction: '0',
  BackdropBrightness: '1',
  BackdropSaturation: '1',
  BackdropContrast: '1',
  BezelWidth: '12',
  BezelScale: '0.35',
  LightAngle: '-45',
  LightIntensity: '1',
  SpecularIntensity: '0',
  SpecularSharpness: '100',
  FresnelStrength: '0',
  ChromaticAberration: '0',
  EdgeLightTop: '0',
  EdgeLightBottom: '0',
  BorderVariance: '0',
  BorderAlphaVariance: '0',
  BorderFresnelBrightness: '0',
  InnerBlur: '0',
  Transform: '',                         // empty = identity
  BorderColor: 'rgba(0, 0, 0, 0)',
  BorderWidth: '0',
  BorderBlur: '0',
  BorderOffset: '0',
  ContainBorder: false,
  BorderBrightness: '1',
  BorderSaturation: '1',
  BorderContrast: '1',
  BorderFrostLodOffset: '0',
  ShadowColor: 'rgba(0, 0, 0, 0)',
  ShadowBlur: '0',
  ShadowOffsetX: '0',
  ShadowOffsetY: '0',
  InnerShadow: false,
  Opacity: '1',
  Visible: true,
  Cursor: 'Default',
  Interactive: false,
  PointerEvents: 'Auto',
  UserSelect: 'Auto',
};
