// Jiv panel rendering — unified shader for glass and non-glass panels.
//
// Port of Jiv.Panel.vert + Jiv.Panel.frag. Instance data comes from a storage
// buffer (replaces 15 vertex attribute locations). The materialType field in
// style_params.w branches between glass (1.0) and non-glass (0.0) paths.
//
// SDF: master superellipse family — one formula, three regimes (Rect, Pill, Circle).
// All clipping, borders, shadows, refraction, and edge lighting use this SDF.

// ─── Bind Groups ────────────────────────────────────────────────────────────
// Group 0: per-frame uniforms + backdrop texture
// Group 1: per-batch instance storage buffer

struct PanelUniforms {
  resolution: vec2f,
  base_frost_lod: f32,
  _pad0: f32,
  specular_tilt: vec2f,
  _pad1: vec2f,
}

struct JivInstance {
  rect: vec4f,           // x, y, w, h (device px)
  panel_geom: vec4f,     // cx, cy, halfW, halfH (device px)
  radii: vec4f,          // tl, tr, br, bl
  tint: vec4f,           // RGBA
  border_color: vec4f,   // RGBA
  shadow_color: vec4f,   // RGBA
  shadow_params: vec4f,  // offsetX, offsetY, blur, borderWidth
  style_params: vec4f,   // borderEdgeAa, smoothness, opacity, materialType
  grading: vec4f,        // brightness, saturation, contrast, frostLod
  refraction: vec4f,     // thickness, bezelWidth, refractionStrength, bezelScale
  lighting: vec4f,       // lightDirX, lightDirY, lightIntensity, fresnelStrength
  specular: vec4f,       // specIntensity, specSharpness, chromaticAberration, innerBlur
  rim_edge: vec4f,       // edgeLightTop, edgeLightBottom, borderVariance, bulge
  outline: vec4f,        // borderAlphaVariance, borderFresnelBrightness, clipOffset, clipCount
  border_filter: vec4f,  // brightnessMul, saturationMul, contrastMul, lodOffset
}

@group(0) @binding(0) var<uniform> uniforms: PanelUniforms;
@group(0) @binding(1) var backdrop: texture_2d<f32>;
@group(0) @binding(2) var backdrop_sampler: sampler;
@group(1) @binding(0) var<storage, read> instances: array<JivInstance>;
// Each clip is 3 vec4s: rect(x,y,w,h), radii(tl,tr,br,bl), meta(smoothness,_,_,_).
// Rect/radii in device pixels; smoothness is unitless (0=circle corners).
@group(2) @binding(0) var<storage, read> clip_stack: array<vec4f>;

// ─── Vertex → Fragment interface ────────────────────────────────────────────

struct VertexOutput {
  @builtin(position) position: vec4f,
  @location(0) pixel_pos: vec2f,
  @location(1) @interpolate(flat) instance_id: u32,
}

// ─── Vertex Shader ──────────────────────────────────────────────────────────

@vertex
fn vs_main(
  @location(0) a_position: vec2f,
  @builtin(instance_index) instance_id: u32,
) -> VertexOutput {
  let inst = instances[instance_id];
  let pos = inst.rect.xy + a_position * inst.rect.zw;

  var clip = (pos / uniforms.resolution) * 2.0 - 1.0;
  clip.y = -clip.y;

  var out: VertexOutput;
  out.position = vec4f(clip, 0.0, 1.0);
  out.pixel_pos = pos;
  out.instance_id = instance_id;
  return out;
}

// ─── Constants ──────────────────────────────────────────────────────────────

const LUMA = vec3f(0.2126, 0.7152, 0.0722);

// Show Studio pill polyline — 33 sample points along upper-right endcap quarter.
// Generated by tests/Pill.PolylineGen.test.ts; do not hand-edit.
const SS_PILL_POINT_COUNT: i32 = 33;
const SS_PILL_MAXEXTENT: f32 = 1.6236;

var<private> SS_PILL_CURVE: array<vec2f, 33> = array<vec2f, 33>(
  vec2f(0.000000, 1.000000), vec2f(0.071905, 0.999903), vec2f(0.141683, 0.999227),
  vec2f(0.209303, 0.997390), vec2f(0.274729, 0.993813), vec2f(0.337929, 0.987916),
  vec2f(0.398867, 0.979119), vec2f(0.457512, 0.966841), vec2f(0.513828, 0.950503),
  vec2f(0.567783, 0.929525), vec2f(0.619341, 0.903327), vec2f(0.668471, 0.871328),
  vec2f(0.715137, 0.832948), vec2f(0.759307, 0.787608), vec2f(0.800946, 0.734728),
  vec2f(0.840021, 0.673727), vec2f(0.874726, 0.607726), vec2f(0.889889, 0.574476),
  vec2f(0.904073, 0.540309), vec2f(0.917279, 0.505288), vec2f(0.929507, 0.469473),
  vec2f(0.940756, 0.432925), vec2f(0.951027, 0.395705), vec2f(0.960321, 0.357875),
  vec2f(0.968635, 0.319495), vec2f(0.975972, 0.280627), vec2f(0.982330, 0.241331),
  vec2f(0.987711, 0.201669), vec2f(0.992113, 0.161702), vec2f(0.995536, 0.121490),
  vec2f(0.997982, 0.081095), vec2f(0.999449, 0.040578), vec2f(0.999938, 0.000000),
);

// ─── SDF Functions ──────────────────────────────────────────────────────────

fn smoothness_to_exponent(s_in: f32) -> f32 {
  let s = clamp(s_in, 0.0, 1.0);
  return 2.0 + 6.0 * s;
}

fn pick_rect_radius(p: vec2f, radii: vec4f) -> f32 {
  // radii = (tl, tr, br, bl)
  if (p.x >= 0.0) {
    return select(radii.z, radii.y, p.y <= 0.0);
  }
  return select(radii.w, radii.x, p.y <= 0.0);
}

// Inside-test for overflow clipping — matches the panel's own squircle
// superellipse so the clip exactly traces the painted rounded-rect edge.
// `smoothness` maps to the same exponent as the panel SDF (n = 2 + 6*s).
fn inside_clip_shape(pixel: vec2f, rect: vec4f, radii: vec4f, smoothness: f32) -> bool {
  let center = rect.xy + rect.zw * 0.5;
  let half_size = rect.zw * 0.5;
  let q_signed = pixel - center;
  let q_abs = abs(q_signed);
  // Outside the bounding box — definitely outside the shape.
  if (q_abs.x > half_size.x || q_abs.y > half_size.y) { return false; }
  let r = pick_rect_radius(q_signed, radii);
  // Inside a "straight" zone (not in any corner box) — inside the shape.
  let corner_p = q_abs - (half_size - vec2f(r, r));
  if (r <= 0.0 || corner_p.x <= 0.0 || corner_p.y <= 0.0) { return true; }
  // Inside a corner box — check the superellipse inequality
  // (cx/r)^n + (cy/r)^n <= 1.
  let n = 2.0 + 6.0 * clamp(smoothness, 0.0, 1.0);
  let L = pow(corner_p.x / r, n) + pow(corner_p.y / r, n);
  return L <= 1.0;
}

// Walk this instance's clip stack entries and return true if `pixel` is
// inside every one. count=0 means no clipping — trivially inside.
fn inside_clip_stack(pixel: vec2f, offset: u32, count: u32) -> bool {
  for (var i: u32 = 0u; i < count; i = i + 1u) {
    let base = (offset + i) * 3u;
    let rect = clip_stack[base];
    let radii = clip_stack[base + 1u];
    let meta = clip_stack[base + 2u];
    if (!inside_clip_shape(pixel, rect, radii, meta.x)) {
      return false;
    }
  }
  return true;
}

// Shape classification: 0=Rect (superellipse), 1=Pill (SS polyline), 2=Circle (ellipse).
// Pill threshold at 1.7× height matches Show Studio Jiv's getEdgeDistanceAndNormal —
// below that aspect the SS pill endcaps overlap and the shape loses its superellipse
// character. Between 1.43 and 1.7, rect mode preserves the squircle profile.
fn shape_mode(half_size: vec2f, radii: vec4f) -> i32 {
  let min_half = min(half_size.x, half_size.y);
  let max_half = max(half_size.x, half_size.y);
  let aspect = max_half / max(min_half, 0.0001);
  let min_radius = min(min(radii.x, radii.y), min(radii.z, radii.w));
  if (aspect < 1.43 && min_radius >= min_half * 0.9) { return 2; }
  if (aspect >= 1.7 && min_radius >= min_half - 1.0) { return 1; }
  return 0;
}

// SS Pill polyline — single-pass SDF + gradient (merged loop).
// Bit-exact equivalent to the old two-pass implementation (proven in
// tests/Pill.SDF.MergedLoop.test.ts across ~715k samples). One polyline scan
// tracks min-distance, closest point, and bracketing segment; bracket short-
// circuits via `bracket_found` flag, distance scan runs to completion.
struct PillEval {
  dist: f32,
  grad: vec2f,
}

fn ss_pill_eval(p: vec2f, half_size: vec2f) -> PillEval {
  var out: PillEval;
  let horiz = half_size.x >= half_size.y;
  let q = select(abs(p.yx), abs(p), horiz);
  let hs = select(half_size.yx, half_size, horiz);
  let half_y = hs.y;
  let half_x = hs.x;
  let max_extent = SS_PILL_MAXEXTENT * half_y;
  let flat_start = half_x - max_extent;

  if (q.x <= flat_start) {
    out.dist = q.y - half_y;
    let g = vec2f(0.0, sign(p.y));
    out.grad = select(g.yx, g, horiz);
    return out;
  }

  let q_l = vec2f(q.x - flat_start, q.y);
  var min_d_sq: f32 = 1e9;
  var best_closest = q_l;
  var u_b: f32 = -1.0;
  var bracket_found = false;

  for (var i: i32 = 0; i < SS_PILL_POINT_COUNT - 1; i++) {
    let a = vec2f(SS_PILL_CURVE[i].x * max_extent, SS_PILL_CURVE[i].y * half_y);
    let b = vec2f(SS_PILL_CURVE[i + 1].x * max_extent, SS_PILL_CURVE[i + 1].y * half_y);
    let ab = b - a;
    let ap = q_l - a;
    let t = clamp(dot(ap, ab) / dot(ab, ab), 0.0, 1.0);
    let closest = a + t * ab;
    let d = q_l - closest;
    let d_sq = dot(d, d);
    if (d_sq < min_d_sq) {
      min_d_sq = d_sq;
      best_closest = closest;
    }
    if (!bracket_found && q_l.y <= a.y && q_l.y >= b.y) {
      let dv = a.y - b.y;
      let tb = select(0.0, (a.y - q_l.y) / dv, dv > 0.0001);
      u_b = mix(a.x, b.x, tb);
      bracket_found = true;
    }
  }

  let u_dist = sqrt(min_d_sq);
  let inside = q_l.y <= half_y && u_b > 0.0 && q_l.x <= u_b;
  out.dist = select(u_dist, -u_dist, inside);

  let dg = q_l - best_closest;
  let l = length(dg);
  var g = select(vec2f(1.0, 0.0), dg / l, l > 0.0001);
  if (inside) { g = -g; }
  g.x *= sign(p.x);
  g.y *= sign(p.y);
  out.grad = select(g.yx, g, horiz);
  return out;
}

// SDF-only entry — shadow pass calls this at p - shadow_offset; no grad needed.
// Same single-pass structure, minus closest-point tracking.
fn ss_pill_sdf(p: vec2f, half_size: vec2f) -> f32 {
  let horiz = half_size.x >= half_size.y;
  let q = select(abs(p.yx), abs(p), horiz);
  let hs = select(half_size.yx, half_size, horiz);
  let half_y = hs.y;
  let half_x = hs.x;
  let max_extent = SS_PILL_MAXEXTENT * half_y;
  let flat_start = half_x - max_extent;

  if (q.x <= flat_start) { return q.y - half_y; }

  let q_l = vec2f(q.x - flat_start, q.y);
  var min_d_sq: f32 = 1e9;
  var u_b: f32 = -1.0;
  var bracket_found = false;

  for (var i: i32 = 0; i < SS_PILL_POINT_COUNT - 1; i++) {
    let a = vec2f(SS_PILL_CURVE[i].x * max_extent, SS_PILL_CURVE[i].y * half_y);
    let b = vec2f(SS_PILL_CURVE[i + 1].x * max_extent, SS_PILL_CURVE[i + 1].y * half_y);
    let ab = b - a;
    let ap = q_l - a;
    let t = clamp(dot(ap, ab) / dot(ab, ab), 0.0, 1.0);
    let closest = a + t * ab;
    let d = q_l - closest;
    min_d_sq = min(min_d_sq, dot(d, d));
    if (!bracket_found && q_l.y <= a.y && q_l.y >= b.y) {
      let dv = a.y - b.y;
      let tb = select(0.0, (a.y - q_l.y) / dv, dv > 0.0001);
      u_b = mix(a.x, b.x, tb);
      bracket_found = true;
    }
  }
  let u_dist = sqrt(min_d_sq);
  let inside = q_l.y <= half_y && u_b > 0.0 && q_l.x <= u_b;
  return select(u_dist, -u_dist, inside);
}

// Gradient-only wrapper — kept for shape_grad dispatch compatibility. Callers
// that need both should use shape_eval to avoid a redundant polyline scan.
fn ss_pill_grad(p: vec2f, half_size: vec2f) -> vec2f {
  return ss_pill_eval(p, half_size).grad;
}

// Master SDF inner (superellipse corner)
fn shape_sdf_inner(p: vec2f, half_size: vec2f, r_axis: vec2f, n: f32) -> f32 {
  let q = abs(p) - half_size + r_axis;
  if (q.x <= 0.0 && q.y <= 0.0) {
    return -min(half_size.x - abs(p.x), half_size.y - abs(p.y));
  }
  let qc = max(q, vec2f(0.0));
  let uv = qc / r_axis;
  let uv_e = max(uv, vec2f(1e-5));
  let un = pow(uv_e.x, n);
  let vn = pow(uv_e.y, n);
  let big_l = pow(un + vn, 1.0 / n);
  let nm1 = n - 1.0;
  let gx = pow(uv_e.x, nm1) / r_axis.x;
  let gy = pow(uv_e.y, nm1) / r_axis.y;
  let lfactor = pow(big_l, 1.0 - n);
  let grad_len = lfactor * sqrt(gx * gx + gy * gy);
  return (big_l - 1.0) / max(grad_len, 1e-5);
}

fn shape_grad_inner(p: vec2f, half_size: vec2f, r_axis: vec2f, n: f32) -> vec2f {
  let q = abs(p) - half_size + r_axis;
  let qc = max(q, vec2f(0.0));
  let uv = qc / r_axis;
  let uv_e = max(uv, vec2f(1e-5));
  let nm1 = n - 1.0;
  var g = vec2f(
    sign(p.x) * pow(uv_e.x, nm1) / r_axis.x,
    sign(p.y) * pow(uv_e.y, nm1) / r_axis.y,
  );
  let g_len = length(g);
  if (g_len < 1e-4) {
    let dx = half_size.x - abs(p.x);
    let dy = half_size.y - abs(p.y);
    return select(vec2f(0.0, sign(p.y)), vec2f(sign(p.x), 0.0), dx < dy);
  }
  return g / g_len;
}

// Unified SDF dispatch
fn shape_sdf(p: vec2f, half_size: vec2f, radii: vec4f, smoothness: f32, mode: i32) -> f32 {
  if (mode == 1) { return ss_pill_sdf(p, half_size); }
  var r_axis: vec2f;
  var n: f32;
  if (mode == 2) {
    // Ellipse — r_axis matches half_size so the shape has continuous curvature
    // everywhere. The old uniform-radius approach created a stadium (flat edges +
    // semicircles) with a C1-but-not-C2 kink at the flat-to-curve junction,
    // visibly non-smooth at narrow aspect ratios.
    r_axis = half_size;
    n = 2.0;
  } else {
    let r = min(pick_rect_radius(p, radii), min(half_size.x, half_size.y));
    r_axis = vec2f(r);
    n = smoothness_to_exponent(smoothness);
  }
  return shape_sdf_inner(p, half_size, r_axis, n);
}

fn shape_grad(p: vec2f, half_size: vec2f, radii: vec4f, smoothness: f32, mode: i32) -> vec2f {
  if (mode == 1) { return ss_pill_grad(p, half_size); }
  var r_axis: vec2f;
  var n: f32;
  if (mode == 2) {
    r_axis = half_size;
    n = 2.0;
  } else {
    let r = min(pick_rect_radius(p, radii), min(half_size.x, half_size.y));
    r_axis = vec2f(r);
    n = smoothness_to_exponent(smoothness);
  }
  return shape_grad_inner(p, half_size, r_axis, n);
}

struct ShapeEval {
  dist: f32,
  grad: vec2f,
}

// Combined dist + gradient. Main shape fragments need both — pill mode does
// a single polyline scan (~4× cheaper than calling shape_sdf and shape_grad
// separately); rect/circle just forwards to the existing pair.
fn shape_eval(p: vec2f, half_size: vec2f, radii: vec4f, smoothness: f32, mode: i32) -> ShapeEval {
  var out: ShapeEval;
  if (mode == 1) {
    let pe = ss_pill_eval(p, half_size);
    out.dist = pe.dist;
    out.grad = pe.grad;
    return out;
  }
  out.dist = shape_sdf(p, half_size, radii, smoothness, mode);
  out.grad = shape_grad(p, half_size, radii, smoothness, mode);
  return out;
}

// ─── Helpers ────────────────────────────────────────────────────────────────

fn apply_grading(color_in: vec3f, brightness: f32, saturation: f32, contrast: f32) -> vec3f {
  var color = color_in * brightness;
  let luma = dot(color, LUMA);
  color = mix(vec3f(luma), color, saturation);
  color = (color - 0.5) * contrast + 0.5;
  return color;
}

fn sample_backdrop(uv: vec2f, extra_lod: f32, frost_lod: f32) -> vec3f {
  let lod = max(0.0, frost_lod - uniforms.base_frost_lod) + extra_lod;
  return textureSampleLevel(backdrop, backdrop_sampler, uv, lod).rgb;
}

// ─── Fragment Shader ────────────────────────────────────────────────────────

@fragment
fn fs_main(in: VertexOutput) -> @location(0) vec4f {
  let inst = instances[in.instance_id];

  // CSS-style overflow clipping — inherited rounded-rect clip stack. Discarding
  // outside any single clip matches the semantics of nested `overflow: hidden`
  // containers with independent `border-radius` values.
  if (!inside_clip_stack(in.pixel_pos, u32(inst.outline.z), u32(inst.outline.w))) {
    discard;
  }

  let panel_center = inst.panel_geom.xy;
  let panel_half_size = inst.panel_geom.zw;
  let shadow_offset = inst.shadow_params.xy;
  let shadow_blur = inst.shadow_params.z;
  let border_width = inst.shadow_params.w;
  let border_edge_aa = inst.style_params.x;
  let smoothness = inst.style_params.y;
  let opacity = inst.style_params.z;
  let material_type = inst.style_params.w;

  let brightness = inst.grading.x;
  let saturation = inst.grading.y;
  let contrast = inst.grading.z;
  let frost_lod = inst.grading.w;

  let thickness = inst.refraction.x;
  let bezel_width = max(inst.refraction.y, 0.5);
  let refraction_strength = inst.refraction.z;
  let bezel_scale = max(inst.refraction.w, 0.05);

  let light_dir = inst.lighting.xy;
  let light_intensity = inst.lighting.z;
  let fresnel_strength = inst.lighting.w;

  let spec_intensity = inst.specular.x;
  let spec_sharpness = max(inst.specular.y, 1.0);
  let chromatic_aberration = inst.specular.z;
  let inner_blur = inst.specular.w;

  let edge_light_top = inst.rim_edge.x;
  let edge_light_bottom = inst.rim_edge.y;
  let border_variance = inst.rim_edge.z;
  let bulge = inst.rim_edge.w;

  let p = in.pixel_pos - panel_center;
  let mode = shape_mode(panel_half_size, inst.radii);

  // SDF + normal — single dispatch for pill mode → one polyline scan instead
  // of two separate scans (SDF + Grad). Rect/circle still uses the cheap
  // closed-form pair.
  let shape = shape_eval(p, panel_half_size, inst.radii, smoothness, mode);
  let dist = shape.dist;
  let edge_dist = max(-dist, 0.0);
  let normal = shape.grad;

  // Bezel hump (pincushion profile)
  let x = edge_dist / bezel_width;
  let s = bezel_scale;
  let hump = clamp((x / s) * exp(1.0 - x / s), 0.0, 1.0);

  // Fill alpha (shape mask)
  let fill_alpha = 1.0 - smoothstep(-0.5, 0.5, dist);
  let aa = max(border_edge_aa, 1e-4);

  // Backdrop sample with refraction + CA + variable LOD
  var backdrop_rgb = vec3f(0.0);
  var lod_boost: f32 = 0.0;
  var base_uv = in.pixel_pos / uniforms.resolution;
  base_uv.y = 1.0 - base_uv.y;

  // Backdrop filter is universal — any jiv with non-default brightness/saturation/
  // contrast/frostLod samples the backdrop, regardless of material. Glass layers
  // refraction + CA + bezel effects on top; flat panels get a clean filtered sample.
  let has_backdrop_filter = abs(brightness - 1.0) > 0.001
    || abs(saturation - 1.0) > 0.001
    || abs(contrast - 1.0) > 0.001
    || frost_lod > uniforms.base_frost_lod + 0.001;

  if (material_type == 1.0) {
    let tangent = vec2f(-normal.y, normal.x);
    let rotated_normal = normal * 0.985 + tangent * 0.174;
    let edge_disp = -rotated_normal * hump * thickness;

    var bulge_disp = vec2f(0.0);
    if (bulge != 0.0) {
      let min_half = min(panel_half_size.x, panel_half_size.y);
      let max_radius = max(panel_half_size.x, panel_half_size.y);
      let norm_dist = clamp(length(p) / max(max_radius, 1.0), 0.0, 1.0);
      let dome_profile = norm_dist * (1.0 - 0.3 * norm_dist);
      let radial_dir = select(vec2f(0.0), p / length(p), length(p) > 0.001);
      let bulge_mag = bulge * min_half * 0.25;
      bulge_disp = radial_dir * dome_profile * bulge_mag;
    }

    let refract_offset = (edge_disp + bulge_disp) * refraction_strength;
    let ca_px = chromatic_aberration * hump * 3.0;
    let ca_step = normal * ca_px;

    base_uv = (in.pixel_pos + refract_offset) / uniforms.resolution;
    let uv_r = (in.pixel_pos + refract_offset + ca_step) / uniforms.resolution;
    let uv_b = (in.pixel_pos + refract_offset - ca_step) / uniforms.resolution;
    base_uv.y = 1.0 - base_uv.y;

    let rim_t = clamp(edge_dist / (bezel_width * 2.5), 0.0, 1.0);
    let rim_boost = (1.0 - rim_t) * (1.0 - rim_t);
    lod_boost = rim_boost * 1.5 + inner_blur * 1.0;
    let s_r = sample_backdrop(vec2f(uv_r.x, 1.0 - uv_r.y), lod_boost, frost_lod);
    let s_g = sample_backdrop(base_uv, lod_boost, frost_lod);
    let s_b = sample_backdrop(vec2f(uv_b.x, 1.0 - uv_b.y), lod_boost, frost_lod);
    backdrop_rgb = vec3f(s_r.r, s_g.g, s_b.b);
    backdrop_rgb = apply_grading(backdrop_rgb, brightness, saturation, contrast);
  } else if (has_backdrop_filter) {
    let s = sample_backdrop(base_uv, 0.0, frost_lod);
    backdrop_rgb = apply_grading(s, brightness, saturation, contrast);
  }

  // Beer-Lambert tint
  if (material_type == 1.0 && inst.tint.a > 0.001) {
    let path_length = mix(0.3, 1.0, smoothstep(0.0, bezel_width * 2.0, edge_dist));
    let absorb = pow(max(inst.tint.rgb, vec3f(0.0001)), vec3f(path_length * inst.tint.a));
    backdrop_rgb *= absorb;
  }

  // Variable border width
  let alignment = dot(normal, light_dir);
  let width_scale = 1.0 + border_variance * alignment;
  let local_border_width = border_width * width_scale;
  let local_border_edge_aa = border_edge_aa * width_scale;

  // Edge lighting
  var edge_light_alpha: f32 = 0.0;
  var edge_light_rgb = vec3f(0.0);
  if (material_type == 1.0 && fill_alpha > 0.0) {
    let rim_band = max(bezel_width * 0.75, 6.0);
    let edge_proximity = select(clamp(1.0 + dist / rim_band, 0.0, 1.0), 0.0, dist > 0.0);
    let falloff = pow(edge_proximity, 1.6);
    let light_facing = max(alignment, 0.0);
    let directional = 0.6 + 0.4 * pow(light_facing, 1.5);
    let rim_uv_raw = (in.pixel_pos - normal * rim_band * 1.2) / uniforms.resolution;
    let rim_uv = vec2f(rim_uv_raw.x, 1.0 - rim_uv_raw.y);
    let rim_sample = sample_backdrop(rim_uv, 0.0, frost_lod);
    let rim_luma = dot(rim_sample, LUMA);
    let rim_vibrant = clamp(mix(vec3f(rim_luma), rim_sample, 1.6) * 1.25, vec3f(0.0), vec3f(1.0));
    let specular_cap = pow(edge_proximity, 3.5);
    edge_light_rgb = mix(rim_vibrant, mix(rim_vibrant, vec3f(1.0), 0.6), specular_cap);
    edge_light_alpha = falloff * directional * fresnel_strength * fill_alpha;
  }

  // Shadow
  let sp = p - shadow_offset;
  let shadow_dist = shape_sdf(sp, panel_half_size, inst.radii, smoothness, mode);
  let shadow_alpha = smoothstep(shadow_blur, -shadow_blur, shadow_dist) * inst.shadow_color.a;

  // Fill — tint composited over backdrop, treated as one material.
  //
  // KEEP-IN-SYNC: Jiv/Shaders/Jiv.Panel.frag. The principle: Background
  // tint is a material property, visible always at its authored alpha.
  // Thickness only controls glass *volume* effects (refraction, Beer-
  // Lambert absorption, fresnel rim, CA) — all of which fade to zero
  // with `glassiness` (smoothstep on thickness). That way both shader
  // variants produce identical pixels for identical inputs, by
  // construction, regardless of where on the Thickness spring a Jiv
  // sits. No variant-boundary seam when a Jiv presses/releases across
  // the glass/non-glass divide. When this WebGPU shader becomes the
  // active path, port the GLSL version's fill block + glassiness-gated
  // Beer-Lambert.
  var fill_rgb: vec3f;
  var fill_a: f32;
  if (material_type == 1.0) {
    fill_rgb = backdrop_rgb;
    fill_a = fill_alpha;
  } else if (has_backdrop_filter) {
    // Flat panel with backdrop filter — tint paints OVER the filtered backdrop.
    // Fill is fully opaque in shape so the filter replaces what was behind (CSS
    // backdrop-filter semantics), then the tint composites over it.
    let t_a = inst.tint.a;
    fill_rgb = inst.tint.rgb * t_a + backdrop_rgb * (1.0 - t_a);
    fill_a = fill_alpha;
  } else {
    fill_rgb = inst.tint.rgb;
    fill_a = fill_alpha * inst.tint.a;
  }

  // Composite: fill OVER shadow
  let out_a = fill_a + shadow_alpha * (1.0 - fill_a);
  let out_rgb = select(
    vec3f(0.0),
    (fill_rgb * fill_a + inst.shadow_color.rgb * shadow_alpha * (1.0 - fill_a)) / out_a,
    out_a > 1e-5,
  );
  var result = vec4f(out_rgb, out_a);

  // Glass-specific compositing
  if (material_type == 1.0) {
    // Hemispherical edge light
    let hemi_top = max(-normal.y, 0.0);
    let hemi_bottom = max(normal.y, 0.0);
    let hemi_ambient = edge_light_top * hemi_top + edge_light_bottom * hemi_bottom;
    let rim_mask = select(
      pow(clamp(1.0 + dist / max(bezel_width, 0.5), 0.0, 1.0), 2.0),
      0.0, dist > 0.0,
    );
    let rim_ambient_rgb = vec3f(hemi_ambient) * rim_mask;

    // Inner darkening
    let inner_pos = bezel_width * 0.35;
    let inner_w = max(thickness * 0.25, 1.2);
    let inner_d = (dist + inner_pos) / inner_w;
    let inner_dark_band = exp(-inner_d * inner_d);
    let inner_dark_alpha = inner_dark_band * 0.04;

    // Blinn-Phong specular catchlight
    let n3 = normalize(vec3f(normal * hump, 1.0 - hump * 0.7));
    let spec_light_dir = normalize(light_dir + uniforms.specular_tilt);
    let l3 = normalize(vec3f(spec_light_dir, 0.6));
    let v3 = vec3f(0.0, 0.0, 1.0);
    let h3 = normalize(l3 + v3);
    let spec_base = pow(max(dot(n3, h3), 0.0), spec_sharpness);
    let spec_alpha = spec_base * spec_intensity * hump * fill_alpha * light_intensity;

    // Composite: hemi + rim glow + inner dark + specular
    result = vec4f(result.rgb + rim_ambient_rgb * fill_alpha, result.a);
    result = vec4f(
      result.rgb * (1.0 - edge_light_alpha) + edge_light_rgb * edge_light_alpha,
      result.a * (1.0 - edge_light_alpha) + edge_light_alpha,
    );
    result = vec4f(result.rgb * (1.0 - inner_dark_alpha), result.a);
    result = vec4f(
      result.rgb * (1.0 - spec_alpha) + vec3f(spec_alpha),
      result.a * (1.0 - spec_alpha) + spec_alpha,
    );

    // Rim specular highlight
    let rim_spec_w = max(thickness * 0.18, 0.75);
    let inside_outline = 1.0 - smoothstep(-aa, aa, dist);
    let within_band = smoothstep(-rim_spec_w - aa, -rim_spec_w + aa, dist);
    let rim_spec_band = inside_outline * within_band;
    let spec_light_dir_rim = normalize(light_dir + uniforms.specular_tilt);
    let rim_spec_align = dot(normal, spec_light_dir_rim);
    let rim_spec_dir = pow(max(rim_spec_align, 0.0), 3.0);
    let rim_spec_alpha = rim_spec_band * rim_spec_dir * spec_intensity * fill_alpha;
    let rim_spec_backdrop = sample_backdrop(base_uv, max(0.0, lod_boost - 0.5), frost_lod);
    let rim_spec_luma = dot(rim_spec_backdrop, LUMA);
    let rim_spec_vibrant = clamp(mix(vec3f(rim_spec_luma), rim_spec_backdrop, 1.8) * 1.4, vec3f(0.0), vec3f(1.0));
    let rim_spec_rgb = mix(rim_spec_vibrant, vec3f(1.0), 0.45);
    result = vec4f(
      result.rgb * (1.0 - rim_spec_alpha) + rim_spec_rgb * rim_spec_alpha,
      result.a * (1.0 - rim_spec_alpha) + rim_spec_alpha,
    );

    // Border zone backdrop refilter
    let border_outer = smoothstep(-aa, aa, dist);
    let border_inner = smoothstep(-aa, aa, dist + local_border_width);
    let border_base = (1.0 - border_outer) * border_inner;
    if (border_base > 0.001) {
      let b_lod = max(0.0, lod_boost + inst.border_filter.w);
      let b_sample = sample_backdrop(base_uv, b_lod, frost_lod);
      let border_backdrop = apply_grading(
        b_sample,
        brightness * inst.border_filter.x,
        saturation * inst.border_filter.y,
        contrast * inst.border_filter.z,
      );
      let light_facing = max(alignment, 0.0);
      let alpha_floor = 1.0 - inst.outline.x;
      let stroke_brightness = mix(alpha_floor, 1.0, pow(light_facing, 2.0));
      let stroke_tint = mix(inst.border_color.rgb, vec3f(1.0), pow(light_facing, 3.0) * inst.outline.y);
      let border_rgb = mix(border_backdrop, stroke_tint, inst.border_color.a * stroke_brightness);
      result = vec4f(mix(result.rgb, border_rgb, border_base), max(result.a, border_base * fill_alpha));
    }
  } else {
    // Non-glass border
    let border_outer = smoothstep(-aa, aa, dist);
    let border_inner = smoothstep(-aa, aa, dist + local_border_width);
    let border_base = (1.0 - border_outer) * border_inner;
    let border_alpha = border_base * inst.border_color.a;
    result = vec4f(
      result.rgb * (1.0 - border_alpha) + inst.border_color.rgb * border_alpha,
      result.a * (1.0 - border_alpha) + border_alpha,
    );
  }

  result = vec4f(result.rgb, result.a * opacity);
  return result;
}
